import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { ArrowRight, BadgeCheck, Bell, Car, Check, ChevronRight, CircleDollarSign, Clock3, Compass, FileCheck2, Flag, Gauge, Home, LayoutDashboard, MapPin, Menu, Navigation, Plus, Search, ShieldCheck, Sparkles, Users, Wallet, X } from 'lucide-react';
import { motion, AnimatePresence } from 'motion/react';
import Lenis from 'lenis';
import './styles.css';

type Role='worker'|'business'|'admin';
type OdcStatus='open'|'filling fast'|'confirmed'|'active'|'completed';
type LobbyStatus='open'|'under review'|'confirmed';
type TripStatus='waiting'|'en route'|'arrived'|'returning';
interface Business{id:string;name:string;industry:string;location:string;verified:boolean;rating:number;active:number;completed:number;logo:string;description:string}
interface Worker{id:string;name:string;age:number;skills:string[];rating:number;completedOdcs:number;verified:boolean;safety:boolean;reliability:number;image:string}
interface Odc{id:string;businessId:string;title:string;category:string;location:string;date:string;time:string;payout:number;required:number;joined:number;status:OdcStatus;distance:string;description:string}
interface Lobby{id:string;odcId:string;workerIds:string[];status:LobbyStatus;fundsSecured:number}
interface Trip{id:string;odcId:string;driver:string;vehicle:string;status:TripStatus;eta:string;pickup:string;destination:string}

const businesses:Business[]=[
{id:'dev',name:'Devanture Technologies',industry:'Technology',location:'HITEC City, Hyderabad',verified:true,rating:4.9,active:4,completed:82,logo:'D',description:'Product engineering and embedded technology company running structured ODC programs across Hyderabad.'},
{id:'north',name:'Northstar Events',industry:'Events',location:'Banjara Hills, Hyderabad',verified:true,rating:4.7,active:2,completed:41,logo:'N',description:'Event operations team coordinating high-volume floor and venue ODC crews.'},
{id:'aster',name:'Aster Retail',industry:'Retail',location:'Kondapur, Hyderabad',verified:true,rating:4.8,active:3,completed:64,logo:'A',description:'Retail operations partner for launches, audits and inventory-intensive ODC work.'},
{id:'metro',name:'Metro Supply Co.',industry:'Logistics',location:'Gachibowli, Hyderabad',verified:true,rating:4.6,active:1,completed:28,logo:'M',description:'Regional supply operations with recurring inventory and dispatch ODCs.'},
];
const workers:Worker[]=[
{id:'w1',name:'Aarav Menon',age:24,skills:['Lab support','Inventory','Excel'],rating:4.9,completedOdcs:34,verified:true,safety:true,reliability:98,image:'AM'},
{id:'w2',name:'Meera Nair',age:27,skills:['Operations','QA','Events'],rating:4.8,completedOdcs:29,verified:true,safety:true,reliability:96,image:'MN'},
{id:'w3',name:'Rahul Das',age:25,skills:['Embedded','Testing','Setup'],rating:4.7,completedOdcs:22,verified:true,safety:true,reliability:94,image:'RD'},
{id:'w4',name:'Ishita Rao',age:23,skills:['Retail','Stock audit'],rating:4.9,completedOdcs:18,verified:true,safety:true,reliability:99,image:'IR'},
];
const odcs:Odc[]=[
{id:'o1',businessId:'dev',title:'Embedded Lab Support',category:'Technology',location:'HITEC City, Hyderabad',date:'18 Sep',time:'09:00 – 18:00',payout:1450,required:12,joined:9,status:'filling fast',distance:'3.2 km',description:'Support the Devanture embedded lab team with setup, device movement, test-bench support and shift documentation.'},
{id:'o2',businessId:'north',title:'Expo Floor Crew',category:'Events',location:'HITEX Exhibition Centre',date:'20 Sep',time:'10:00 – 19:00',payout:1650,required:18,joined:14,status:'filling fast',distance:'5.8 km',description:'Guest movement, booth setup support and end-of-day floor operations for a technology expo.'},
{id:'o3',businessId:'aster',title:'Retail Launch Team',category:'Retail',location:'Kondapur, Hyderabad',date:'22 Sep',time:'08:00 – 17:00',payout:1250,required:10,joined:6,status:'open',distance:'7.4 km',description:'Assist launch-day merchandising, stock movement and store readiness for a new-format retail opening.'},
{id:'o4',businessId:'metro',title:'Inventory Count Crew',category:'Logistics',location:'Gachibowli, Hyderabad',date:'24 Sep',time:'07:30 – 16:30',payout:1350,required:16,joined:8,status:'open',distance:'9.1 km',description:'Structured inventory count and warehouse reconciliation shift with team lead support.'},
];
const lobbySeed:Lobby={id:'l1',odcId:'o1',workerIds:['w1','w2','w3'],status:'open',fundsSecured:17400};
const tripSeed:Trip={id:'t1',odcId:'o1',driver:'Driver 04',vehicle:'Toyota Innova · TS 09 EX 2404',status:'waiting',eta:'18 min',pickup:'Worker pickup cluster · HITEC City',destination:'Devanture Technologies'};

function App(){
 const [role,setRole]=useState<Role>('worker');
 const [view,setView]=useState('home');
 const [selectedOdc,setSelectedOdc]=useState<Odc>(odcs[0]);
 const [lobby,setLobby]=useState<Lobby>(lobbySeed);
 const [trip,setTrip]=useState<Trip>(tripSeed);
 const [checkedIn,setCheckedIn]=useState(false);
 const [checkedOut,setCheckedOut]=useState(false);
 const [menu,setMenu]=useState(false);
 const [toast,setToast]=useState('');
 useEffect(()=>{ const l=new Lenis({duration:1.05,smoothWheel:true}); let raf=(t:number)=>{l.raf(t);requestAnimationFrame(raf)};requestAnimationFrame(raf); return()=>l.destroy();},[]);
 useEffect(()=>{if(!toast)return;const t=setTimeout(()=>setToast(''),2600);return()=>clearTimeout(t)},[toast]);
 const business=businesses.find(b=>b.id===selectedOdc.businessId)!;
 const activeOdc=odcs[0];
 const join=()=>{setLobby(v=>({...v,workerIds:v.workerIds.includes('w1')?v.workerIds:[...v.workerIds,'w1']}));setToast('You joined the ODC lobby. Awaiting business confirmation.');setView('active')};
 const confirmWorker=()=>{setLobby(v=>({...v,status:'confirmed'}));setToast('Worker confirmed. Payment is now secured.')};
 const dispatch=()=>{setTrip(v=>({...v,status:'en route',eta:'9 min'}));setToast('Driver 04 dispatched. Pickup is on the way.')};
 const checkin=()=>{setCheckedIn(true);setTrip(v=>({...v,status:'arrived',eta:'Arrived'}));setToast('Check-in recorded with location verification.')};
 const checkout=()=>{setCheckedOut(true);setToast('ODC completed. ₹1,450 payout is processing.')};
 return <div className="app">
   <header className="topbar"><button className="brand" onClick={()=>{setRole('worker');setView('home')}}><span className="brand-mark">E</span><span>EASYWORK</span></button><div className="top-center"><span className="live-dot"/>ODC network live <span className="muted">· Hyderabad</span></div><div className="top-actions"><button className="icon-btn"><Bell size={17}/></button><button className="profile-chip" onClick={()=>setMenu(!menu)}><span className="avatar small">AM</span><span>Demo account</span><ChevronRight size={15}/></button></div></header>
   {menu&&<div className="role-menu"><div className="eyebrow">DEMO ENVIRONMENT</div><button onClick={()=>{setRole('worker');setView('home');setMenu(false)}}><span>Worker</span><small>ODC discovery + journey</small></button><button onClick={()=>{setRole('business');setView('overview');setMenu(false)}}><span>Business</span><small>Devanture operations</small></button><button onClick={()=>{setRole('admin');setView('overview');setMenu(false)}}><span>Admin</span><small>Operational command center</small></button><div className="demo-note">No driver login. Drivers are dispatched resources controlled by EasyWork.</div></div>}
   {role==='worker'?<WorkerApp {...{view,setView,selectedOdc,setSelectedOdc,join,lobby,trip,checkedIn,checkedOut,checkin,checkout}}/>:<Workspace {...{role,view,setView,lobby,confirmWorker,dispatch,trip,setTrip}}/>}
   <AnimatePresence>{toast&&<motion.div initial={{y:30,opacity:0}} animate={{y:0,opacity:1}} exit={{y:20,opacity:0}} className="toast"><Check size={16}/>{toast}</motion.div>}</AnimatePresence>
 </div>
}

function WorkerApp(p:any){
 const biz=businesses.find((b:Business)=>b.id===p.selectedOdc.businessId)!;
 const nav=[['home',Home,'Home'],['odcs',Compass,'ODCs'],['active',Navigation,'Active ODC'],['history',Clock3,'History'],['earnings',Wallet,'Earnings'],['safety',ShieldCheck,'Safety'],['profile',Users,'Profile']];
 return <><div className="worker-shell"><aside className="sidebar"><div className="eyebrow">WORKER</div><div className="cert-card"><div className="cert-ring"><ShieldCheck size={18}/></div><div><b>Certified</b><span>ODC-ready profile</span></div></div>{nav.map(([id,I,label]:any)=><button className={p.view===id?'nav-item active':''} onClick={()=>p.setView(id)} key={id}><I size={17}/><span>{label}</span></button>)}<div className="sidebar-spacer"/><div className="mini-trust"><BadgeCheck size={16}/><div><b>Verified identity</b><small>Safety training active</small></div></div></aside>
   <main className="main"><div className="mobile-nav"><button className="icon-btn"><Menu size={18}/></button><span>Worker</span><button className="icon-btn"><Search size={18}/></button></div>{renderWorkerPage(p,biz)}</main></div><div className="mobile-tabs">{nav.slice(0,5).map(([id,I,label]:any)=><button onClick={()=>p.setView(id)} className={p.view===id?'active':''} key={id}><I size={17}/><span>{label}</span></button>)}</div></>
}
function renderWorkerPage(p:any,biz:Business){
 if(p.view==='home')return <HomePage {...p} biz={biz}/>;
 if(p.view==='odcs')return <div className="page"><SectionHeader kicker="ODC DISCOVERY" title="Find organised work, not job listings." desc="Nearby, structured engagements with verified businesses, fixed shifts and secured payouts."/><div className="segmented"><button className="selected">Nearby ODCs</button><button>All ODCs</button><button>Categories</button></div><div className="odc-grid">{odcs.map(o=><OdcCard key={o.id} odc={o} onClick={()=>{p.setSelectedOdc(o);p.setView('detail')}}/>)}</div></div>;
 if(p.view==='detail')return <OdcDetail {...p} biz={biz}/>;
 if(p.view==='active')return <ActiveOdc {...p} biz={biz}/>;
 if(p.view==='history')return <HistoryPage/>;
 if(p.view==='earnings')return <EarningsPage/>;
 if(p.view==='safety')return <SafetyPage/>;
 return <ProfilePage/>;
}
function HomePage({setView,setSelectedOdc,join,lobby,trip,checkedIn,checkedOut}:any){return <div className="page home-page"><div className="hero-row"><div><div className="eyebrow">GOOD MORNING, AARAV</div><h1>Your next ODC is already taking shape.</h1><p className="hero-copy">Verified businesses. Organised lobbies. Secured money. Managed transport.</p><div className="hero-actions"><button className="btn lime" onClick={()=>setView('odcs')}>Explore ODCs <ArrowRight size={16}/></button><button className="text-btn" onClick={()=>setView('profile')}>View certified profile</button></div></div><div className="cert-hero"><div className="hero-metric"><span>YOUR STATUS</span><strong>CERTIFIED</strong><small>Identity + safety verified</small></div><ShieldCheck size={92} strokeWidth={1.25}/></div></div><div className="stats-grid"><Metric label="Nearby ODCs" value="12" suffix="within 10 km"/><Metric label="Next payout" value="₹1,450" suffix="secured after confirmation"/><Metric label="Reliability" value="98%" suffix="based on ODC history"/><Metric label="Completed" value="34" suffix="ODCs completed"/></div><div className="section-heading"><div><div className="eyebrow">NEARBY · HIGH CONFIDENCE</div><h2>ODCs around you</h2></div><button className="text-btn" onClick={()=>setView('odcs')}>View all <ArrowRight size={14}/></button></div><div className="home-grid"><OdcCard odc={odcs[0]} featured onClick={()=>{setSelectedOdc(odcs[0]);setView('detail')}}/><div className="map-card"><div className="map-top"><div><span className="map-label">NETWORK VIEW</span><b>3.2 km to Devanture</b></div><span className="pill lime-pill">9 / 12 joined</span></div><div className="map-surface"><div className="map-line line-a"/><div className="map-line line-b"/><div className="map-dot worker-dot"/><div className="map-dot odc-dot"/><div className="map-dot driver-dot"/><div className="map-label-box pickup">PICKUP</div><div className="map-label-box dest">ODC · DEVANTURE</div></div><div className="map-footer"><span><i className="dot worker"/> You</span><span><i className="dot odc"/> ODC</span><span><i className="dot driver"/> Dispatch</span></div></div></div><div className="journey-strip"><JourneyStep n="01" label="Join lobby" done={lobby.workerIds.includes('w1')}/><JourneyStep n="02" label="Business confirms" done={lobby.status==='confirmed'}/><JourneyStep n="03" label="Payment secured" done={lobby.status==='confirmed'}/><JourneyStep n="04" label="Driver dispatched" done={trip.status!=='waiting'}/><JourneyStep n="05" label="Check in" done={checkedIn}/><JourneyStep n="06" label="Paid" done={checkedOut}/></div></div>}
function OdcCard({odc,onClick,featured=false}:any){const b=businesses.find(x=>x.id===odc.businessId)!;return <motion.button whileHover={{y:-3}} className={'odc-card '+(featured?'featured':'')} onClick={onClick}><div className="odc-card-top"><div className="company-mark">{b.logo}</div><span className={'status '+odc.status.replace(' ','-')}>{odc.status.toUpperCase()}</span></div><div className="eyebrow">{odc.category} · {odc.distance}</div><h3>{odc.title}</h3><div className="company-line"><span>{b.name}</span>{b.verified&&<BadgeCheck size={14}/>}</div><div className="odc-detail-row"><span><Clock3 size={14}/>{odc.date} · {odc.time}</span><span><MapPin size={14}/>{odc.location}</span></div><div className="payout-row"><div><span>SECURED PAYOUT</span><strong>₹{odc.payout.toLocaleString('en-IN')}</strong></div><div className="seats"><span>LOBBY</span><strong>{odc.joined} / {odc.required}</strong></div></div><div className="progress"><i style={{width:`${odc.joined/odc.required*100}%`}}/></div><div className="odc-card-foot"><span>{odc.required-odc.joined} seats remaining</span><span>View ODC <ArrowRight size={14}/></span></div></motion.button>}
function OdcDetail({selectedOdc,p:_,setView,join,biz,lobby}:any){return <div className="page detail-page"><button className="back-btn" onClick={()=>setView('odcs')}>← Back to ODCs</button><div className="detail-grid"><div><div className="odc-cover"><div className="cover-orbit orbit-1"/><div className="cover-orbit orbit-2"/><div className="cover-badge"><BadgeCheck size={15}/>{biz.name} · Verified Business</div><div className="cover-code">ODC · {selectedOdc.id.toUpperCase()}</div></div><div className="detail-main"><div className="eyebrow">{selectedOdc.category}</div><h1>{selectedOdc.title}</h1><p className="lead">{selectedOdc.description}</p><div className="detail-facts"><Fact icon={Clock3} label="DATE & SHIFT" value={`${selectedOdc.date} · ${selectedOdc.time}`}/><Fact icon={MapPin} label="LOCATION" value={`${selectedOdc.location} · ${selectedOdc.distance}`}/><Fact icon={Users} label="WORKERS" value={`${selectedOdc.required} required · ${selectedOdc.required-selectedOdc.joined} seats left`}/><Fact icon={CircleDollarSign} label="PAYMENT" value={`₹${selectedOdc.payout.toLocaleString('en-IN')} secured / worker`}/></div><div className="detail-sections"><section><div className="eyebrow">WORKER REQUIREMENTS</div><div className="tag-row"><span>Basic lab operations</span><span>9h shift</span><span>Safety briefing</span><span>Team collaboration</span></div></section><section><div className="eyebrow">WHAT IS INCLUDED</div><ul className="clean-list"><li>Managed pickup and return transport</li><li>Attendance verified at the ODC location</li><li>Secured payout released after completion</li></ul></section></div></div></div><aside className="sticky-panel"><div className="eyebrow">LOBBY STATUS</div><div className="lobby-number"><strong>{selectedOdc.joined}</strong><span>/ {selectedOdc.required} joined</span></div><div className="progress big"><i style={{width:`${selectedOdc.joined/selectedOdc.required*100}%`}}/></div><p>{selectedOdc.required-selectedOdc.joined} seats remaining. This lobby is filling fast.</p><div className="money-box"><span>YOUR POTENTIAL PAYOUT</span><strong>₹{selectedOdc.payout.toLocaleString('en-IN')}</strong><small>Payment is secured after business confirmation.</small></div><div className="trust-list"><div><ShieldCheck size={17}/><span>Verified business</span></div><div><Wallet size={17}/><span>Funds secured before work</span></div><div><Car size={17}/><span>Managed transport both ways</span></div></div><button className="btn lime full" onClick={join}>{lobby.workerIds.includes('w1')?'LOBBY JOINED':'JOIN ODC LOBBY'} <ArrowRight size={16}/></button><small className="micro">Joining a lobby is not final confirmation. Devanture reviews participating workers.</small></aside></div></div>}
function ActiveOdc({lobby,trip,checkedIn,checkedOut,checkin,checkout,setView}:any){return <div className="page active-page"><SectionHeader kicker="ACTIVE ODC" title="Your day, controlled end to end." desc="One operational timeline from confirmation through return home."/><div className="active-status-row"><StatusBlock label="LOBBY" value={lobby.status==='confirmed'?'CONFIRMED':'UNDER REVIEW'} ok={lobby.status==='confirmed'}/><StatusBlock label="PAYMENT" value={lobby.status==='confirmed'?'₹1,450 SECURED':'PENDING'} ok={lobby.status==='confirmed'}/><StatusBlock label="TRANSPORT" value={trip.status.toUpperCase()} ok={trip.status!=='waiting'}/><StatusBlock label="ATTENDANCE" value={checkedIn?'CHECKED IN':'NOT STARTED'} ok={checkedIn}/></div><div className="timeline-card"><TimelineItem n="01" label="Joined ODC lobby" meta="18 Sep · 07:42" done/><TimelineItem n="02" label="Business confirmation" meta={lobby.status==='confirmed'?'Confirmed by Devanture':'Waiting for business review'} done={lobby.status==='confirmed'}/><TimelineItem n="03" label="Payment secured" meta={lobby.status==='confirmed'?'₹1,450 reserved':'Locked until confirmation'} done={lobby.status==='confirmed'}/><TimelineItem n="04" label="Driver dispatch" meta={trip.status==='waiting'?'Waiting to dispatch':`${trip.driver} · ${trip.eta}`} done={trip.status!=='waiting'}/><TimelineItem n="05" label="ODC check-in" meta={checkedIn?'Location verified':'At destination, ready to check in'} done={checkedIn}/><TimelineItem n="06" label="ODC complete + payout" meta={checkedOut?'₹1,450 paid':'Release after check-out'} done={checkedOut}/></div>{trip.status!=='waiting'&&<div className="transport-card"><div><div className="eyebrow">MANAGED TRANSPORT</div><h3>{trip.status==='arrived'?'You arrived at the ODC':'Driver is on the way'}</h3><p>{trip.vehicle} · {trip.driver}</p></div><div className="eta">{trip.eta}</div></div>}{!checkedOut&&<div className="active-cta">{lobby.status!=='confirmed'?<div className="waiting-banner"><Clock3 size={18}/><div><b>Waiting for business confirmation</b><span>Your place is held in the lobby. EasyWork will secure payment once Devanture confirms.</span></div></div>:trip.status==='waiting'?<div className="waiting-banner"><Car size={18}/><div><b>Payment secured. Transport next.</b><span>EasyWork will dispatch your pickup group once the ODC is ready.</span></div></div>:!checkedIn?<button className="btn lime" onClick={checkin}>CHECK IN <MapPin size={16}/></button>:<button className="btn lime" onClick={checkout}>CHECK OUT <Check size={16}/></button>}</div>}<button className="text-btn" onClick={()=>setView('safety')}>Open Safety Center <ShieldCheck size={14}/></button></div>}
function HistoryPage(){return <div className="page"><SectionHeader kicker="ODC HISTORY" title="Proof of work, not a profile feed." desc="A clean operational record of the ODCs you've completed."/><div className="history-list">{[['Embedded QA Support','Devanture Technologies','₹1,450','18 Aug'],['Retail Audit Crew','Aster Retail','₹1,250','03 Aug'],['Expo Floor Crew','Northstar Events','₹1,650','27 Jul']].map((x,i)=><div className="history-item" key={i}><div className="history-index">0{i+1}</div><div className="history-main"><b>{x[0]}</b><span>{x[1]} · Completed</span></div><div className="history-money"><b>{x[2]}</b><span>{x[3]}</span></div><BadgeCheck size={17}/></div>)}</div></div>}
function EarningsPage(){return <div className="page"><SectionHeader kicker="EARNINGS" title="Money with a clear chain of custody." desc="Every payout maps back to an ODC, attendance record and completion state."/><div className="earnings-hero"><div><span className="eyebrow">TOTAL EARNED</span><strong>₹38,650</strong><span>34 completed ODCs</span></div><div className="earnings-chart">{[40,68,52,78,61,84,72].map((h,i)=><i key={i} style={{height:`${h}%`}}/>)}</div></div><div className="payment-row"><span>18 Sep · Embedded Lab Support</span><strong>₹1,450 <em>SECURED</em></strong></div><div className="payment-row"><span>03 Aug · Retail Audit Crew</span><strong>₹1,250 <em>PAID</em></strong></div></div>}
function SafetyPage(){return <div className="page"><SectionHeader kicker="SAFETY CENTER" title="Support that follows you to the ODC." desc="Your trip, emergency contact and reporting tools stay one tap away."/><div className="safety-grid"><div className="safety-dark"><ShieldCheck size={27}/><div className="eyebrow">ACTIVE PROTECTION</div><h2>Trip protection is live.</h2><p>EasyWork logs your pickup, route, arrival and attendance. SOS routes directly to operations.</p><button className="btn danger">SOS / GET HELP</button></div><div className="safety-card"><div className="eyebrow">EMERGENCY CONTACT</div><h3>Priya Menon</h3><p>+91 98••• ••240</p><button className="outline-btn">Call contact</button></div><div className="safety-card"><div className="eyebrow">CURRENT TRIP</div><h3>Driver 04</h3><p>Toyota Innova · TS 09 EX 2404</p><span className="status en-route">EN ROUTE</span></div></div></div>}
function ProfilePage(){const w=workers[0];return <div className="page"><SectionHeader kicker="CERTIFIED WORKER PROFILE" title="A professional operational identity." desc="Not a social profile. A verified record of capability, reliability and ODC history."/><div className="profile-layout"><div className="profile-card"><div className="profile-head"><div className="avatar large">{w.image}</div><div><div className="certified-pill"><BadgeCheck size={15}/> CERTIFIED</div><h2>{w.name}</h2><p>Hyderabad · Available for technology ODCs</p></div></div><div className="profile-metrics"><Metric label="Reliability" value="98%"/><Metric label="ODCs completed" value="34"/><Metric label="Worker rating" value="4.9"/></div><div className="profile-tags">{w.skills.map(s=><span key={s}>{s}</span>)}</div></div><div className="verification-panel"><div className="eyebrow">VERIFICATION</div>{[['Identity verified',true],['Safety training',true],['Experience history',true],['Payment details',true]].map(([x,v]:any)=><div className="verify-row" key={x}><span>{x}</span><BadgeCheck size={16}/></div>)}<div className="eyebrow top-gap">PREFERENCES</div><div className="pref-row"><span>Working radius</span><b>10 km</b></div><div className="pref-row"><span>Preferred categories</span><b>Tech · Retail</b></div></div></div></div>}
function Workspace({role,view,setView,lobby,confirmWorker,dispatch,trip}:any){const isBusiness=role==='business';const nav=isBusiness?['Overview','ODCs','Lobbies','Workers','Attendance','Payments','History','Reports','Profile']:['Overview','ODCs','Workers','Businesses','Verification','Transport','Payments','Safety','Reports'];const v=view==='overview'?'Overview':view[0]?.toUpperCase()+view.slice(1);return <div className="workspace"><aside className="ops-sidebar"><div className="eyebrow">{isBusiness?'BUSINESS CONSOLE':'EASYWORK OPERATIONS'}</div><div className="ops-brand">{isBusiness?'DEVANTURE':'EASYWORK'}<small>{isBusiness?'Verified business':'Admin command center'}</small></div>{nav.map(n=><button className={v===n?'active':''} key={n} onClick={()=>setView(n.toLowerCase())}>{n}</button>)}<div className="sidebar-spacer"/><div className="ops-user"><span className="avatar small">{isBusiness?'D':'EW'}</span><div><b>{isBusiness?'Devanture Admin':'Operations'}</b><span>{isBusiness?'Verified business':'Admin'}</span></div></div></aside><main className="ops-main"><div className="ops-top"><div><span className="eyebrow">{isBusiness?'DEVANTURE TECHNOLOGIES':'AIR TRAFFIC CONTROL'}</span><h1>{isBusiness?'Business operations, organised.':'Live ODC operations, one command surface.'}</h1></div><button className="btn lime" onClick={()=>setView(isBusiness?'create':'transport')}>{isBusiness?<><Plus size={16}/>CREATE ODC</>:<><Car size={16}/>DISPATCH BOARD</>}</button></div>{isBusiness?(<BusinessDashboard {...{lobby,confirmWorker}}/>):(<AdminDashboard {...{trip,dispatch}}/>)}<div className="demo-strip"><Sparkles size={15}/> Demo mode · no production authentication or payment credentials are connected.</div></main></div>}
function BusinessDashboard({lobby,confirmWorker}:any){return <div className="ops-grid"><div className="ops-stat-row"><Metric label="Active ODCs" value="4" suffix="2 need action"/><Metric label="Workers today" value="31" suffix="9 pending confirmation"/><Metric label="Secured funds" value="₹52,840" suffix="across active lobbies"/><Metric label="Attendance" value="97.8%" suffix="this month"/></div><div className="ops-main-card"><div className="card-head"><div><div className="eyebrow">ODC LOBBY · DEV-2409</div><h2>Embedded Lab Support</h2></div><span className="status filling-fast">FILLING FAST</span></div><div className="lobby-summary"><div><span>Workers</span><strong>{lobby.workerIds.length + 6} / 12</strong></div><div><span>Funds secured</span><strong>₹17,400</strong></div><div><span>Shift</span><strong>18 Sep · 09:00</strong></div><div><span>Status</span><strong>{lobby.status==='confirmed'?'CONFIRMED':'UNDER REVIEW'}</strong></div></div><div className="table-like"><div className="table-head"><span>WORKER</span><span>RELIABILITY</span><span>HISTORY</span><span>STATUS</span><span>ACTION</span></div>{workers.slice(0,3).map((w:Worker,i:number)=><div className="worker-row" key={w.id}><div className="worker-name"><span className="avatar tiny">{w.image}</span><span><b>{w.name}</b><small>{w.skills[0]}</small></span></div><strong>{w.reliability}%</strong><span>{w.completedOdcs} ODCs</span><span className="verified-text"><BadgeCheck size={14}/> Verified</span>{i===0&&lobby.status!=='confirmed'?<button className="mini-btn" onClick={confirmWorker}>CONFIRM</button>:<button className="mini-btn">VIEW</button>}</div>)}</div></div><div className="side-stack"><div className="side-card"><div className="eyebrow">BUSINESS TRUST</div><div className="trust-score"><strong>4.9</strong><span>★ · worker rating</span></div><p>82 ODCs completed · 100% payment funding history</p></div><div className="side-card"><div className="eyebrow">TRANSPORT</div><h3>Managed by EasyWork</h3><p>Pickup groups are dispatched automatically after confirmation.</p><span className="status confirmed">READY</span></div></div></div>}
function AdminDashboard({trip,dispatch}:any){const rows=[['DEV-2409','Devanture Technologies','9 workers','Driver 04','EN ROUTE'],['EVT-1842','Northstar Events','13 workers','Driver 11','PICKUP IN 12 MIN'],['RET-7710','Aster Retail','6 workers','—','WAITING']];return <div className="ops-grid"><div className="ops-stat-row"><Metric label="ODCs live" value="18" suffix="+4 from yesterday"/><Metric label="Workers active" value="142" suffix="across 31 ODCs"/><Metric label="Drivers available" value="11" suffix="24 dispatched"/><Metric label="Payments secured" value="₹4.8L" suffix="today"/></div><div className="dispatch-card"><div className="card-head"><div><div className="eyebrow">TODAY · TRANSPORT</div><h2>Dispatch board</h2></div><span className="pill dark-pill">LIVE</span></div><div className="dispatch-map"><div className="map-surface ops-map"><div className="route route-1"/><div className="route route-2"/><div className="dispatch-pin p1"/><div className="dispatch-pin p2"/><div className="dispatch-pin p3"/><span className="ops-map-title">HYDERABAD ODC NETWORK</span></div></div><div className="dispatch-table">{rows.map((r,i)=><div className="dispatch-row" key={r[0]}><div><span className="eyebrow">{r[0]}</span><b>{r[1]}</b></div><span>{r[2]}</span><span>{r[3]}</span><span className={i<2?'status confirmed':'status open'}>{r[4]}</span><button className="mini-btn" onClick={i===2?dispatch:undefined}>{i===2?'DISPATCH':'VIEW TRIP'}</button></div>)}</div></div><div className="side-stack"><div className="side-card"><div className="eyebrow">SAFETY</div><h3>1 incident needs review</h3><p>All active trips remain visible to operations.</p><button className="outline-btn">OPEN SAFETY</button></div><div className="side-card"><div className="eyebrow">VERIFICATION QUEUE</div><h3>8 businesses</h3><p>6 worker documents · 2 business profiles</p><button className="outline-btn">REVIEW QUEUE</button></div></div></div>}
function SectionHeader({kicker,title,desc}:any){return <div className="section-header"><div className="eyebrow">{kicker}</div><h1>{title}</h1><p>{desc}</p></div>}
function Fact({icon:Icon,label,value}:any){return <div className="fact"><Icon size={17}/><span>{label}</span><b>{value}</b></div>}
function Metric({label,value,suffix}:any){return <div className="metric"><span>{label}</span><strong>{value}</strong>{suffix&&<small>{suffix}</small>}</div>}
function JourneyStep({n,label,done}:any){return <div className={'journey-step '+(done?'done':'')}><span>{done?<Check size={14}/>:n}</span><b>{label}</b></div>}
function TimelineItem({n,label,meta,done}:any){return <div className={'timeline-item '+(done?'done':'')}><span className="timeline-n">{done?<Check size={14}/>:n}</span><div><b>{label}</b><small>{meta}</small></div></div>}
function StatusBlock({label,value,ok}:any){return <div className={'status-block '+(ok?'ok':'')}><span>{label}</span><strong>{value}</strong></div>}

createRoot(document.getElementById('root')!).render(<App/>);
